### ISSUE TITLE
Bug: error occurs when using GltfGen to load an image from a URL on Heroku

### ISSUE THREAD

**Issue by AndreMuis** [Microsoft/mixed-reality-extension-sdk#169]
This occurs even when using http instead of https. Could be Heroku specific but works locally and direct link works:

http://altspacevr-demo.herokuapp.com/beach-ball.png

Logs:

2019-02-03T22:09:33.164165+00:00 heroku[web.1]: State changed from down to starting
2019-02-03T22:09:32.968886+00:00 app[api]: Deploy c37a4d16 by user andre@andremuis.com
2019-02-03T22:09:32.968886+00:00 app[api]: Release v41 created by user andre@andremuis.com
2019-02-03T22:09:35.000000+00:00 app[api]: Build succeeded
2019-02-03T22:09:40.812472+00:00 heroku[web.1]: State changed from starting to up
2019-02-03T22:13:12.610023+00:00 heroku[router]: at=info method=GET path="/" host=altspacevr-demo.herokuapp.com request_id=a1af1ce7-294b-49f9-80fc-11bd3a0b1279 fwd="77.248.202.248" dyno=web.1 connect=1ms service=45105ms status=101 bytes=2673 protocol=http
2019-02-03T22:14:22.975545+00:00 heroku[router]: at=info method=GET path="/" host=altspacevr-demo.herokuapp.com request_id=c265e6b6-f91f-416b-ae0e-8438e57b548b fwd="107.77.109.87" dyno=web.1 connect=1ms service=162276ms status=101 bytes=129 protocol=http
2019-02-03T22:14:29.005916+00:00 app[web.1]: unhandledRejection Error: An unexpected error occurred while loading the asset [MixedRealityExtension.Assets.AssetSource]. The trace is below:
2019-02-03T22:14:29.005932+00:00 app[web.1]: System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (No connection could be made because the target machine actively refused it.
2019-02-03T22:14:29.005935+00:00 app[web.1]: at UnityGLTF.Loader.WebRequestLoader+<LoadStream>d__8.MoveNext () [0x000be] in <2801c65e3cbd456796e895b4820afce9>:0
2019-02-03T22:14:29.005936+00:00 app[web.1]: at MixedRealityExtension.Assets.AssetLoader+<LoadAssetsFromGLTF>d__11.MoveNext () [0x000d3] in <1bd02526ba564e2383a5a3f09d73901c>:0
2019-02-03T22:14:29.005938+00:00 app[web.1]: at MixedRealityExtension.Assets.AssetLoader+<LoadAssets>d__10.MoveNext () [0x000e1] in <1bd02526ba564e2383a5a3f09d73901c>:0
2019-02-03T22:14:29.005940+00:00 app[web.1]: at AssetManager.loadGltfHelper (/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/types/runtime/assets/assetManager.js:74:19)
2019-02-03T22:14:29.005942+00:00 app[web.1]: at processTicksAndRejections (internal/process/next_tick.js:81:5)

[logs.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2826076/logs.txt)

[gltf-gen-image-url.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2826071/gltf-gen-image-url.ts.txt)

**Comment by stevenvergenz** [comment]
Hmm, "connection refused" doesn't sound like an SDK bug. Double check your heroku settings?

**Comment by AndreMuis** [comment]
Looks like you have to tell Heroku exactly what the base URL is for your app otherwise it will use some form of localhost. See attached screenshot for an example of how to configure this. 

![capture](https://user-images.githubusercontent.com/920149/52293216-2f92e780-292b-11e9-97a5-2486963df6a4.PNG)
