### ISSUE TITLE
Error: WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by stevenvergenz** [Microsoft/mixed-reality-extension-sdk#177]
My app server is spamming these errors, then eventually crashing. My guess is that the SDK is trying to send messages to users that are mid-disconnect?

```
unhandledRejection Error: WebSocket is not open: readyState 2 (CLOSING)
at WebSocket.send (/opt/app/node_modules/ws/lib/websocket.js:322:19)
at WebSocket.on (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/connection/webSocket.js:38:26)
at WebSocket.emit (events.js:189:13)
at WebSocket.EventEmitter.emit (domain.js:441:20)
at WebSocket.send (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/connection/eventedConnection.js:36:14)
at ClientSync.sendMessage (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/protocols/protocol.js:67:19)
at Promise (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/adapters/multipeer/protocols/clientSync.js:183:19)
at new Promise ()
at ClientSync.sendAndExpectResponse (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/adapters/multipeer/protocols/clientSync.js:182:16)
at ClientSync.createActor (/opt/app/node_modules/@microsoft/mixed-reality-extension-sdk/built/adapters/multipeer/protocols/clientSync.js:164:25)
```

**Comment by eanders-MS** [comment]
What version of the SDK?

**Comment by stevenvergenz** [comment]
v0.5.0

**Comment by eanders-MS** [comment]
v0.6.0 handles this condition much better. Give it a try and let me know if you're still seeing a crash.
