### ISSUE TITLE
[animation-test] Test did not cleanup all actors

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#498]
Functional test running on localhost in MRETestBed, single user joined. Red branch.

Running animation-test, after pressing the Return button, some actors did not get cleaned up and there was an error message in the MRE's log:

```
2020-03-05T01:27:26.171Z app TypeError: Cannot read property 'cleanup' of null
    at App.stopTest (C:\code\Microsoft\mixed-reality-extension-sdk\packages\functional-tests\built\app.js:130:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

![image](https://user-images.githubusercontent.com/12176807/75949061-f4c6f000-5e59-11ea-9782-326dc1cc4cf3.png)

**Comment by stevenvergenz** [comment]
Fixed in 0.17.
