### ISSUE TITLE
[v0.18.n - animate-to] failed to sync user on re-enter

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#575]
unhandledRejection TypeError: **Cannot read property 'update' of undefined**  at constructor.stage:create-animations (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:78:115)  at ClientSync.executeStage (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:167:19)  at ClientSync.run (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:184:32)  at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by eanders-MS** [comment]
Same callstack occurred in the grab test upon user re-enter.
